import "./Receipt.css";
import { printReceipt } from "../utils/printReceipt";

import logo from "../assets/logo.png";
import qr from "../assets/qr.png";
import stamp from "../assets/stamp.png";
import signature from "../assets/signature.png";

function formatMoney(value) {
  return `₹ ${Number(value || 0).toLocaleString("en-IN")}`;
}

function formatDate(value) {
  if (!value) return "-";

  return new Date(value).toLocaleDateString("en-IN");
}

export default function Receipt({ customer, payment }) {
  const balance =
    Number(customer.total_amount || 0) -
    Number(customer.amount_paid || 0);

  return (
    <div className="receipt-page">

      <div className="receipt">

        {/* Header */}

        <div className="receipt-header">

          <div className="logo-box">
            <img src={logo} alt="" />
          </div>

          <div className="company">

            <h1>R DREAM INFRA DEVELOPERS</h1>

            <p>
              DTCP Approved Open Plots |
              Konyapalem Venture
            </p>

            <h2>PAYMENT RECEIPT</h2>

          </div>

        </div>

        {/* Info */}

        <div className="top-info">

          <div>
            <b>Receipt No</b>

            <span>{payment.receipt_number}</span>
          </div>

          <div>

            <b>Date</b>

            <span>
              {formatDate(payment.payment_date)}
            </span>

          </div>

        </div>

        {/* Cards */}

        <div className="cards">

          <div className="card">

            <h3>Customer Information</h3>

            <table>

              <tbody>

                <tr>

                  <td>Name</td>

                  <td>{customer.name}</td>

                </tr>

                <tr>

                  <td>Phone</td>

                  <td>{customer.phone}</td>

                </tr>

                <tr>

                  <td>Booking</td>

                  <td>
                    {formatDate(customer.booking_date)}
                  </td>

                </tr>

                <tr>

                  <td>Status</td>

                  <td>{customer.status}</td>

                </tr>

              </tbody>

            </table>

          </div>

          <div className="card">

            <h3>Plot Information</h3>

            <table>

              <tbody>

                <tr>

                  <td>Plot</td>

                  <td>{customer.plot_no}</td>

                </tr>

                <tr>

                  <td>Size</td>

                  <td>{customer.plot_size} Sq.Yds</td>

                </tr>

                <tr>

                  <td>Facing</td>

                  <td>{customer.facing}</td>

                </tr>

                <tr>

                  <td>Road</td>

                  <td>{customer.road_width}</td>

                </tr>

              </tbody>

            </table>

          </div>

        </div>

        {/* Payment */}

        <div className="payment">

          <h3>Payment Summary</h3>

          <table>

            <tbody>

              <tr>

                <td>Total Amount</td>

                <td>{formatMoney(customer.total_amount)}</td>

              </tr>

              <tr>

                <td>Amount Paid</td>

                <td>{formatMoney(customer.amount_paid)}</td>

              </tr>

              <tr>

                <td>Current Payment</td>

                <td>{formatMoney(payment.amount)}</td>

              </tr>

              <tr>

                <td>Balance</td>

                <td>{formatMoney(balance)}</td>

              </tr>

              <tr>

                <td>Payment Mode</td>

                <td>{payment.payment_mode}</td>

              </tr>

              <tr>

                <td>Transaction ID</td>

                <td>{payment.transaction_id}</td>

              </tr>

            </tbody>

          </table>

        </div>

        {/* Declaration */}

        <div className="declaration">

          <h3>Declaration</h3>

          <p>

            Received the above payment towards the
            purchase of the above plot.

            This receipt is generated by
            <b> R DREAM INFRA DEVELOPERS </b>

            and is valid without a physical signature.

          </p>

        </div>

        {/* Footer */}

        <div className="footer">

          <div>

            <img src={qr} alt="" />

            <p>Scan QR</p>

          </div>

          <div>

            <img src={stamp} alt="" />

            <p>Company Stamp</p>

          </div>

          <div>

            <img
              src={signature}
              alt=""
            />

            <p>Authorized Signature</p>

          </div>

        </div>

        <button
          className="download"
          onClick={() =>
            printReceipt(customer, payment)
          }
        >

          Download PDF

        </button>

      </div>

    </div>
  );
}